const express = require('express');
const router = express.Router();
const { prepare } = require('../db');
const state = require('./taksi-state');

// GET /taksi -> Render main dashboard page
router.get('/', async (req, res) => {
  try {
    const categories = await prepare('SELECT * FROM categories ORDER BY name').all();
    res.render('taksi', { categories, session: req.session });
  } catch (err) {
    console.error('Error loading categories for taksi page:', err.message);
    res.render('taksi', { categories: [], session: req.session });
  }
});

// GET /taksi/api/queue -> Proxy queue data (bypass CORS)
router.get('/api/queue', async (req, res) => {
  try {
    const data = await state.fetchQueueData();
    res.json({ success: true, data });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /taksi/api/subscribe -> Register or update a taxi driver alert subscription
router.post('/api/subscribe', (req, res) => {
  try {
    const {
      clientId, // unique persistent ID generated by client browser localStorage
      ntfyTopic,
      sehiriciEnabled,
      sehiriciRangeStart,
      sehiriciRangeEnd,
      sehirdisiEnabled,
      sehirdisiRangeStart,
      sehirdisiRangeEnd
    } = req.body;

    if (!clientId) {
      return res.status(400).json({ success: false, error: 'clientId zorunludur.' });
    }

    if (!ntfyTopic || ntfyTopic.trim() === '') {
      return res.status(400).json({ success: false, error: 'ntfy konu adı boş olamaz.' });
    }

    // Find if subscription already exists for this client
    let sub = state.activeSubscriptions.find(s => s.clientId === clientId);
    
    if (sub) {
      // Update existing
      sub.ntfyTopic = String(ntfyTopic).trim();
      sub.sehiriciEnabled = Boolean(sehiriciEnabled);
      sub.sehiriciRangeStart = parseInt(sehiriciRangeStart, 10);
      sub.sehiriciRangeEnd = parseInt(sehiriciRangeEnd, 10);
      sub.sehirdisiEnabled = Boolean(sehirdisiEnabled);
      sub.sehirdisiRangeStart = parseInt(sehirdisiRangeStart, 10);
      sub.sehirdisiRangeEnd = parseInt(sehirdisiRangeEnd, 10);
      sub.lastUpdated = Date.now();
      
      // Reset sent status for sehirici if range changed
      if (sub.lastSehiriciVal !== undefined) delete sub.lastSehiriciVal;
      if (sub.lastSehirdisiVal !== undefined) delete sub.lastSehirdisiVal;
      
      console.log(`[Taksi] Abonelik güncellendi: Client: ${clientId}, Topic: ${sub.ntfyTopic}`);
    } else {
      // Create new
      sub = {
        clientId,
        ntfyTopic: String(ntfyTopic).trim(),
        sehiriciEnabled: Boolean(sehiriciEnabled),
        sehiriciRangeStart: parseInt(sehiriciRangeStart, 10),
        sehiriciRangeEnd: parseInt(sehiriciRangeEnd, 10),
        sehirdisiEnabled: Boolean(sehirdisiEnabled),
        sehirdisiRangeStart: parseInt(sehirdisiRangeStart, 10),
        sehirdisiRangeEnd: parseInt(sehirdisiRangeEnd, 10),
        lastUpdated: Date.now()
      };
      state.activeSubscriptions.push(sub);
      console.log(`[Taksi] Yeni abonelik eklendi: Client: ${clientId}, Topic: ${sub.ntfyTopic}`);
    }

    state.saveSubscriptions();
    res.json({ success: true, message: 'Takip başarıyla başlatıldı!' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /taksi/api/test-push -> Trigger immediate test push notification
router.post('/api/test-push', async (req, res) => {
  try {
    const { topic } = req.body;
    if (!topic || topic.trim() === '') {
      return res.status(400).json({ success: false, error: 'Lütfen geçerli bir ntfy kanal adı girin.' });
    }

    const testMsg = `Deneme Bildirimi: Telefon bağlantınız başarıyla kuruldu! Sıra takip uyarısı bu kanaldan gelecektir.`;
    await state.sendPushNotification(topic, testMsg, '🔔 Test Uyarisi', 'white_check_mark,tada');
    
    res.json({ success: true, message: 'Test bildirimi telefona gönderildi!' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
